const data1 = {
  batch_inf: '到货批次表',
  enterprise_inf: '往来单位信息表',
  first_component_inventory: '一级核心部件库存与采购能力表',
  first_keyprocess_inf: '一级供应商瓶颈工序',
  first_purchase_from_second: '二级采购表',
  first_supplier_inf: '一级供应商表',
  orderdetail: '订单追踪信息',
  second_ability_inf: '二级产存检运能力表',
  second_supplier_inf: '二级供应商表',
  sys_depart: '部门表',
  sys_user: '工作人员表',
  order_inf: '订单表',
  product_inf: '产品信息表',
  component_inf: '核心部件表',
  first_purchase: '一级采购表',
  simulation_inf: '仿真记录与文件表'
}
const data2 = {
  create_time: '创建时间',
  stuff_id: '人员编号',
  stuff_name: '姓名',
  department: '部门',
  order_id: '订单编号',
  update_time: '录入时间',
  delivery_date: '交货期',
  product_id: '产品编号',
  purchase_cycle: '供货周期',
  first_supplier_id: '供应商编号',
  first_purchaseid: '一级采购编号',
  purchase_time: '采购时间',
  bottleneck_sid: '采购瓶颈供应商',
  purchase_percent: '采购比例',
  purchase_quantity: '采购数量',
  purchase_lead_time: '采购提前期',
  real_delivery_date: '实际交货期',
  product_name: '产品名称',
  product_type: '产品类别',
  product_specification: '产品规格',
  product_unit: '产品计量单位',
  product_nature: '产品性质',
  supplier_name: '供应商名称',
  first_supplier_id: '一级供应商编号',
  supplier_simple_name: '供应商简称',
  supplier_address: '供应商地址',
  contact: '联系人',
  contact_num: '联系电话',
  tax_id: '税号',
  private_enterprise: '是否民口企业',
  battleneck_supplier: '是否瓶颈供应商',
  certification: '供应商资质',
  legal_person: '法定代表人',
  post_code: '邮编',
  bank_name: '开户行名称',
  bank_account: '开户账号',
  etp_id: '往来单位信息 id',
  is_product: '是否生产瓶颈供应商',
  is_purchase: '是否采购瓶颈供应商',
  estab_year: '成立年份',
  corporate_credit: '企业征信',
  product_stock: '产品库存',
  production_lot: '生产批量',
  day_pro_lot: '日均产量',
  max_day_pro_lot: '日最大生产量',
  production_cycle: '生产周期（天）',
  check_time_A: 'A 组检验周期（天）',
  check_time_B: 'B 组检验周期（天）',
  check_time_C: 'C 组检验周期（天）',
  check_time_D: 'D 组检验周期（天）',
  transport_time_description: '检验周期（天）逻辑关系',
  transport_time: '运输周期（天）',
  com1_inf_id: '核心部件编号',
  first_supplier_id: '一级供应商编号',
  stock_quantity: '库存数量',
  purchase_lead_time: '采购周期（天）',
  second_supplier_id: '二级供应商编号',
  component_id: '核心部件编号',
  delivery_date: '约定交货期限',
  actual_delivery_time: '实际交货日期',
  component_name: '部件名称',
  component_specification: '部件规格',
  component_unit: '部件计量单位',
  component_nature: '部件性质',
  legal_person: '法定代表人',
  dailyproductioncapacity: '日均产量',
  admin_regin: '行政区域',
  permit_id: '许可证编号',
  lot_id: '批次编号',
  arrival_quantity: '到货数量',
  arrival_data: '到货时间',
  pass_rate: '批次合格率',
  batch_number: '总批次量',
  keyprocess: '瓶颈工序名称',
  simulation_id: '仿真编号',
  simulation_purpose: '仿真目的',
  smulation_version: '版本',
  report_file: '报告文件',
  model_file: '模型文件',
  input_time: '仿真时间',
  purchase1_id: '采购订单号',
  supply_cycle: '供应周期',
  first_purchase_id: '一级采购编号'
}

export const CHTableName = new Map(Object.entries(data1))
export const CHTableField = new Map(Object.entries(data2))
